### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by rmsul** [spmeesseman/vscode-extjs#2]
Hi, i just install your ext and when start - error.

[2021-12-05 13:42:01.108] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
	at validateString (internal/validators.js:124:11)
	at Object.join (path.js:375:7)
	at t.ConfigParser.parseAppDotJson (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:811293)
	at async t.ConfigParser.parseAppDotJsonFiles (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:809572)
	at async t.ConfigParser.getConfig (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:809080)
	at async t.default.initializeInternal (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:799041)
	at async t.default.initialize (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:799286)
	at async t.activate (c:\Users\User\.vscode\extensions\spmeesseman.vscode-extjs-0.14.1\dist\client\extension.js:1:79907)
	at async Promise.all (index 6)
	at async Promise.all (index 0)

My settings:
{
    "git.ignoreWindowsGit27Warning": true,
    "explorer.confirmDelete": false,
    "workbench.startupEditor": "none",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
    "editor.quickSuggestions": true,
    "liveServer.settings.CustomBrowser": "chrome",
    "[vue]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "files.associations": {
        "*.json": "jsonc"
    },
    "extjsIntellisense.frameworkDirectory": "D:\\Sencha\\ext-7.3.0\\"
}

.extjsrc.json
{
    "name": "SApp",
    "classpath": "app"
}

+ extensions not see in app.json classpath as array.
"classpath":  [ "app" ]

**Comment by spmeesseman** [comment]
any chance u could post you app.json?

**Comment by aurban6** [comment]
Hi
Problem is  packages.dir in workspace.json

**Comment by aurban6** [comment]
I found a problem in my file workspace.json
`    "frameworks": {
        "ext": {
            "path":"ext",
            "version":"6.5.2.463"
        }
    },`
this configuration caused an error,
change on 
`     "frameworks":
     {
         "ext": "ext"
     },`
IS OK :) :) :) :)

I'm sorry for the trouble

Thanks for the great extension

**Comment by spmeesseman** [comment]
@aurban6, ill add support for the object value version of the 'ext' property.  As I get feedback like this, the extension will become better and better as far as "just working" right away.  I can't code for it if I've never seen it, I went through a ton of that getting my Task Explore extension to where it is now.   Thanks for writing back!

**Comment by rmsul** [comment]
> change on ` "frameworks": { "ext": "ext" },` IS OK :) :) :) :)

Confirm problem solved.

**Comment by spmeesseman** [comment]
ill add support for this in the next build.  thanks both of you guys for reporting back!
